language: ruby

rvm:
  - "2.2"

sudo: false

install: echo install

script: echo script

deploy:
  provider: rubygems
  api_key:
    master:
      secure: "G54sBU9xA5zN1xS1PRToGO/VsIaIhC0wEPah61bCwlnUVC5i+O9QcP0ujtyR397OvFT4ZgJ2qC4I8+2oOedWpRDXfV30VvL7eoB3K2Off5WWPvmVJqBnuOj6gNLsPEC6R0hLgyfbxKr6beJyKVvIpaPrtU12LHDBBZ5m00k4myM="
  gem:
    master: "social_snippet-registry_views"
  on:
    repo: social-snippet/social-snippet-registry-views

